name: ResearchChain
channels:
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.9.3=py38hae2e43d_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.3.0=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - beautifulsoup4=4.12.3=pyha770c72_0
  - brotli-python=1.0.9=py38h4cd09af_9
  - ca-certificates=2024.2.2=h8857fd0_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=py38hecd8cb5_0
  - dataclasses-json=0.6.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - frozenlist=1.4.1=py38hae2e43d_0
  - googlesearch=3.0.0=pyh9f0ad1d_0
  - greenlet=2.0.2=py38h4cd09af_0
  - idna=3.6=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py38h50d1736_3
  - langchain=0.1.11=pyhd8ed1ab_0
  - langchain-community=0.0.27=pyhd8ed1ab_0
  - langchain-core=0.1.30=pyhd8ed1ab_0
  - langchain-text-splitters=0.0.1=pyhd8ed1ab_0
  - langsmith=0.1.23=pyhd8ed1ab_0
  - libblas=3.9.0=21_osx64_openblas
  - libcblas=3.9.0=21_osx64_openblas
  - libcxx=16.0.6=hd57cbcb_0
  - libffi=3.4.4=hecd8cb5_0
  - libgfortran=5.0.0=13_2_0_h97931a8_3
  - libgfortran5=13.2.0=h2873a65_3
  - liblapack=3.9.0=21_osx64_openblas
  - libopenblas=0.3.26=openmp_hfef2a42_0
  - llvm-openmp=17.0.6=hb6ac08f_0
  - marshmallow=3.21.1=pyhd8ed1ab_0
  - multidict=6.0.5=py38hef030d1_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=hcec6c5f_0
  - numpy=1.24.2=py38h5a2dcdf_0
  - openssl=3.2.1=hd75f5a5_0
  - orjson=3.9.15=py38hd96bad9_0
  - packaging=23.2=pyhd8ed1ab_0
  - pip=23.3.1=py38hecd8cb5_0
  - pydantic=2.6.3=pyhd8ed1ab_0
  - pydantic-core=2.16.3=py38h3614dca_0
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=h5ee71fb_0
  - python_abi=3.8=2_cp38
  - pyyaml=6.0.1=py38hcafd530_1
  - readline=8.2=hca72f7f_0
  - regex=2023.12.25=py38hae2e43d_0
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=68.2.2=py38hecd8cb5_0
  - sniffio=1.3.1=pyhd8ed1ab_0
  - soupsieve=2.5=pyhd8ed1ab_1
  - sqlalchemy=2.0.28=py38hae2e43d_0
  - sqlite=3.41.2=h6c40b1e_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tiktoken=0.5.2=py38h0c33575_0
  - tk=8.6.12=h5d9f67b_0
  - typing-extensions=4.10.0=hd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.41.2=py38hecd8cb5_0
  - xz=5.4.6=h6c40b1e_0
  - yaml=0.2.5=h0d85af4_2
  - yarl=1.9.4=py38hae2e43d_0
  - zlib=1.2.13=h4dc903c_0
  - pip:
      - faiss-cpu==1.8.0
prefix: /usr/local/Caskroom/miniconda/base/envs/ResearchChain
