name: ResearchChain
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - aiohttp=3.9.1=py38h01eb140_0
  - aiosignal=1.3.1=pyhd8ed1ab_0
  - annotated-types=0.6.0=pyhd8ed1ab_0
  - anyio=4.2.0=pyhd8ed1ab_0
  - async-timeout=4.0.3=pyhd8ed1ab_0
  - attrs=23.2.0=pyh71513ae_0
  - brotli-python=1.0.9=py38hfa26641_7
  - ca-certificates=2024.2.2=hbcca054_0
  - certifi=2024.2.2=py38h06a4308_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=py38h06a4308_0
  - cudatoolkit=11.8.0=h4ba93d1_13
  - dataclasses-json=0.6.4=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_2
  - faiss=1.7.4=py38cuda112h48d0473_0_cuda
  - frozenlist=1.4.1=py38h01eb140_0
  - greenlet=1.1.2=py38hfa26641_2
  - iniconfig=2.0.0=pyhd8ed1ab_0
  - jsonpatch=1.33=pyhd8ed1ab_0
  - jsonpointer=2.4=py38h578d9bd_3
  - langchain=0.1.5=pyhd8ed1ab_0
  - langchain-community=0.0.18=pyhd8ed1ab_0
  - langchain-core=0.1.21=pyhd8ed1ab_0
  - langsmith=0.0.87=pyhd8ed1ab_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libblas=3.9.0=21_linux64_openblas
  - libcblas=3.9.0=21_linux64_openblas
  - libfaiss=1.7.4=cuda112hb18a002_0_cuda
  - libfaiss-avx2=1.7.4=cuda112h1234567_0_cuda
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libgomp=13.2.0=h807b86a_5
  - liblapack=3.9.0=21_linux64_openblas
  - libopenblas=0.3.26=pthreads_h413a1c8_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - marshmallow=3.20.2=pyhd8ed1ab_0
  - multidict=6.0.5=py38h01eb140_0
  - mypy_extensions=1.0.0=pyha770c72_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.2.1=hd590300_0
  - pip=24.0=pyhd8ed1ab_0
  - pluggy=1.4.0=pyhd8ed1ab_0
  - pydantic=2.6.1=pyhd8ed1ab_0
  - pydantic-core=2.16.2=py38h0cc4f7c_1
  - pysocks=1.7.1=pyha2e5f31_6
  - pytest=8.0.0=pyhd8ed1ab_0
  - pytest-subtests=0.11.0=pyhd8ed1ab_0
  - python=3.8.18=h955ad1f_0
  - python_abi=3.8=2_cp38
  - pyyaml=6.0.1=py38h01eb140_1
  - readline=8.2=h5eee18b_0
  - regex=2023.10.3=py38h5eee18b_0
  - requests=2.31.0=pyhd8ed1ab_0
  - setuptools=68.2.2=py38h06a4308_0
  - sniffio=1.3.0=pyhd8ed1ab_0
  - sqlalchemy=2.0.25=py38h01eb140_0
  - sqlite=3.41.2=h5eee18b_0
  - tenacity=8.2.3=pyhd8ed1ab_0
  - tiktoken=0.5.2=py38h788434f_0
  - tk=8.6.12=h1ccaba5_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - typing_inspect=0.9.0=pyhd8ed1ab_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.5=h5eee18b_0
  - yaml=0.2.5=h7f98852_2
  - yarl=1.9.4=py38h01eb140_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - backoff==2.2.1
      - beautifulsoup4==4.12.3
      - chardet==5.2.0
      - click==8.1.7
      - deepdiff==6.7.1
      - diskcache==5.6.3
      - emoji==2.11.0
      - filelock==3.13.4
      - filetype==1.2.0
      - fsspec==2024.3.1
      - google==3.0.0
      - huggingface-hub==0.22.2
      - idna==3.7
      - jinja2==3.1.3
      - joblib==1.3.2
      - jsonpath-python==1.0.6
      - langdetect==1.0.9
      - llama-cpp-python==0.2.61
      - lxml==5.1.1
      - markupsafe==2.1.5
      - nltk==3.8.1
      - numpy==1.24.4
      - ordered-set==4.1.0
      - packaging==24.0
      - pypdf==4.1.0
      - python-dateutil==2.9.0.post0
      - python-iso639==2024.2.7
      - python-magic==0.4.27
      - rapidfuzz==3.7.0
      - six==1.16.0
      - soupsieve==2.5
      - tabulate==0.9.0
      - tinydb==4.8.0
      - tqdm==4.66.2
      - typing-extensions==4.11.0
      - unstructured==0.11.8
      - unstructured-client==0.22.0
      - urllib3==2.2.1
      - wrapt==1.16.0
